name: Release CityVault

on:
  push:
    tags:
      - 'v*'  # e.g. v0.1.3

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for pushing

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version.json in main
        run: |
          echo "{ \"version\": \"${VERSION}\" }" > data/version.json
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/version.json
          git commit -m "Update version.json to ${VERSION}" || echo "No changes"
          git push

      - name: Create ZIP artifact
        run: |
          mkdir dist
          zip -r "dist/cityvault-${VERSION}.zip" . -x "*.git*" "node_modules/*"

      - name: Upload Release ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: dist/cityvault-${VERSION}.zip

      - name: Update update.json in gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

          echo '{
            "latest": "'${VERSION}'",
            "url": "https://github.com/${{ github.repository }}/releases/download/v${VERSION}/cityvault-${VERSION}.zip",
            "notes": "See https://github.com/${{ github.repository }}/releases/tag/v${VERSION}"
          }' > update.json

          git add update.json
          git commit -m "Update update.json for v${VERSION}" || echo "No changes"
          git push origin gh-pages
